### PR TITLE
Main: Added offline transaction signing

### PR DESCRIPTION
**Pull request by mullroy**
Added offline transaction signing

### CODE REVIEW

**Comment by crocket** [comment]
Does it add offline signing for both CLI and GUI?

**Comment by crocket** [comment]
I invite you to https://github.com/PirateNetwork/PirateWallet-Lite/issues/3

**Comment by mullroy** [comment]
Good day,

Sorry for the late reply. I've lately only been on the Discord channels.

Its currently only for CLI. I still have to do the GUI integration.

Regards,

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by mullroy** [comment]
GUI integration added for off-line transaction signing.

**Comment by crocket** [comment]
I'm just curious. How do you build it? I can't build full node wallet on gentoo linux.

**Comment by mullroy** [comment]
Good day,

1) Check out the source code from GIT:
git clone https://github.com/PirateNetwork/pirate
2) Enter the repository: cd pirate
3) Enter the build directory: cd zcutil
There are a variety of build scripts. The source code depends on a bunch of
external libraries. Once you start the build the 'depends' will be downloaded
first, which is approx 750mb. That will be build first and then the actual wallet
build will get underway.
On Linux, launch the build with: ./build-qt-linux.sh
If the build was successful, the binary will be in the root of your repository,
called: pirate-qt-linux

On Friday, 7 May 2021 00:28, crocket ***@***.***> wrote:
I'm just curious. How do you build it? I can't build full node wallet on gentoo linux.

**Comment by CryptoForge** [comment]
@mullroy I moved the pull request to the Dev branch to work on implementing it.

**Pull request merged**
